baseURL = "https://mannilito.github.io/Notion-Hugo-Presentation/"
languageCode = "en-us"
title = "Interaction in Space"
theme = ["DoIt"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
